routes/web.php
<?php

Route::redirect('/', '/login');
Route::redirect('/home', '/admin');
Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
    Route::post('/make_order', 'OrderController@make_order');
    Route::post('/send_to', 'OrderController@send_to');
    Route::post('/send_to_typo', 'OrderController@send_to_typo');
    Route::post('/receive', 'MyStoreController@receive');
    Route::post('/spisat', 'MyStoreController@spisat');
    Route::post('/dobavit', 'MyStoreController@dobavit');

    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Book Packs
    Route::delete('book-packs/destroy', 'BookPacksController@massDestroy')->name('book-packs.massDestroy');
    Route::resource('book-packs', 'BookPacksController');

    // Books
    Route::delete('books/destroy', 'BookController@massDestroy')->name('books.massDestroy');
    Route::resource('books', 'BookController');

    // Stores
    Route::delete('stores/destroy', 'StoreController@massDestroy')->name('stores.massDestroy');
    Route::resource('stores', 'StoreController');

    // Orders
    Route::delete('orders/destroy', 'OrderController@massDestroy')->name('orders.massDestroy');
    Route::resource('orders', 'OrderController');

    // My Stores
    Route::delete('my-stores/destroy', 'MyStoreController@massDestroy')->name('my-stores.massDestroy');
    Route::resource('my-stores', 'MyStoreController');
});

resources/views/partials/datatablesActions.blade.php
@can($viewGate)
    <a class="btn btn-xs btn-primary" href="{{ route('admin.' . $crudRoutePart . '.show', $row->id) }}">
        {{ trans('global.view') }}
    </a>
@endcan
@if(isset($order))
@can($order)
        <input type="text" name="book_{{$row->id}}" value="0" class="form-control">
        <!--<input type="hidden" name="book_id{{$row->id}}" value="{{$row->id}}">!-->
@endcan
@endif

@if(isset($send_typo) && $row->status=="0")
@can($send_typo)
    <form action="/admin/send_to_typo" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <input type="hidden" name="order_id" value="{{$row->id}}">
        <input type="submit" class="btn btn-xs btn-success" value="Отправить в типографию">
    </form>
@endcan
@endif

@if(isset($send) && $row->status!="2")
@can($send)
    <form action="/admin/send_to" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <input type="hidden" name="order_id" value="{{$row->id}}">
        <input type="text" name="book_number" value="0" class="form-control">
        <input type="submit" class="btn btn-xs btn-success" value="Отправить получателю">
    </form>
@endcan
@endif

@if(isset($receive) && $row->status!="3")
@can($receive)
    <form action="/admin/receive" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <input type="hidden" name="order_id" value="{{$row->id}}">
        <input type="submit" class="btn btn-xs btn-success" value="Принять на склад">
    </form>
@endcan
@endif

@can($editGate)
    <a class="btn btn-xs btn-info" href="{{ route('admin.' . $crudRoutePart . '.edit', $row->id) }}">
        {{ trans('global.edit') }}
    </a>
@endcan
@can($deleteGate)
    <form action="{{ route('admin.' . $crudRoutePart . '.destroy', $row->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
        <input type="hidden" name="_method" value="DELETE">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
    </form>
@endcan

resources/views/partials/menu.blade.php
<aside class="main-sidebar">
    <section class="sidebar" style="height: auto;">
        <ul class="sidebar-menu tree" data-widget="tree">
            <!--
            <li>
                <a href="{{ route("admin.home") }}">
                    <i class="fas fa-fw fa-tachometer-alt">

                    </i>
                    {{ trans('global.dashboard') }}
                </a>
            </li>!-->
            
            @can('user_management_access')
                <li class="treeview">
                    <a href="#">
                        <i class="fa-fw fas fa-users">

                        </i>
                        <span>{{ trans('cruds.userManagement.title') }}</span>
                        <span class="pull-right-container"><i class="fa fa-fw fa-angle-left pull-right"></i></span>
                    </a>
                    <ul class="treeview-menu">
                        @can('permission_access')
                            <li class="{{ request()->is('admin/permissions') || request()->is('admin/permissions/*') ? 'active' : '' }}">
                                <a href="{{ route("admin.permissions.index") }}">
                                    <i class="fa-fw fas fa-unlock-alt">

                                    </i>
                                    <span>{{ trans('cruds.permission.title') }}</span>
                                </a>
                            </li>
                        @endcan
                        @can('role_access')
                            <li class="{{ request()->is('admin/roles') || request()->is('admin/roles/*') ? 'active' : '' }}">
                                <a href="{{ route("admin.roles.index") }}">
                                    <i class="fa-fw fas fa-briefcase">

                                    </i>
                                    <span>{{ trans('cruds.role.title') }}</span>
                                </a>
                            </li>
                        @endcan
                        @can('user_access')
                            <li class="{{ request()->is('admin/users') || request()->is('admin/users/*') ? 'active' : '' }}">
                                <a href="{{ route("admin.users.index") }}">
                                    <i class="fa-fw fas fa-user">

                                    </i>
                                    <span>{{ trans('cruds.user.title') }}</span>
                                </a>
                            </li>
                        @endcan
                    </ul>
                </li>
            @endcan
            
            @can('book_access')
                <li class="{{ request()->is('admin/books') || request()->is('admin/books/*') ? 'active' : '' }}">
                    <a href="{{ route("admin.books.index") }}">
                        <i class="fa-fw fas fa-cogs">

                        </i>
                        <span>{{ trans('cruds.book.title') }}</span>
                    </a>
                </li>
            @endcan
            @can('book_pack_access')
                <li class="{{ request()->is('admin/book-packs') || request()->is('admin/book-packs/*') ? 'active' : '' }}">
                    <a href="{{ route("admin.book-packs.index") }}">
                        <i class="fa-fw fas fa-cogs">

                        </i>
                        <span>{{ trans('cruds.bookPack.title') }}</span>
                    </a>
                </li>
            @endcan
            @can('store_access')
                <li class="{{ request()->is('admin/stores') || request()->is('admin/stores/*') ? 'active' : '' }}">
                    <a href="{{ route("admin.stores.index") }}">
                        <i class="fa-fw fas fa-cogs">

                        </i>
                        <span>{{ trans('cruds.store.title') }}</span>
                    </a>
                </li>
            @endcan
            @can('order_access')
                <li class="{{ request()->is('admin/orders') || request()->is('admin/orders/*') ? 'active' : '' }}">
                    <a href="{{ route("admin.orders.index") }}">
                        <i class="fa-fw fas fa-cogs">

                        </i>
                        <span>{{ trans('cruds.order.title') }}</span>
                    </a>
                </li>
            @endcan
            @can('my_store_access')
                <li class="{{ request()->is('admin/my-stores') || request()->is('admin/my-stores/*') ? 'active' : '' }}">
                    <a href="{{ route("admin.my-stores.index") }}">
                        <i class="fa-fw fas fa-cogs">

                        </i>
                        <span>{{ trans('cruds.myStore.title') }}</span>
                    </a>
                </li>
            @endcan
            <li>
                <a href="#" onclick="event.preventDefault(); document.getElementById('logoutform').submit();">
                    <i class="fas fa-fw fa-sign-out-alt">

                    </i>
                    {{ trans('global.logout') }}
                </a>
            </li>
        </ul>
    </section>
</aside>